[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info

[program:server]
command=node /app/server/src/index.js
directory=/app/server
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=NODE_ENV="production",PORT="8080",OUTPUT_DIR="%(ENV_OUTPUT_DIR)s"

[program:walker]
command=/app/venv/bin/python /app/walker/walker.py
directory=/app/walker
autostart=false
autorestart=false
startretries=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=OUTPUT_DIR="%(ENV_OUTPUT_DIR)s",GOOGLE_API_KEY="%(ENV_GOOGLE_API_KEY)s",PYTHONUNBUFFERED="1"
